CREATE TYPE "UserRole" AS ENUM ('PATIENT', 'DOCTOR', 'ADMIN');
CREATE TYPE "AppointmentStatus" AS ENUM ('PENDING', 'BOOKED', 'CONFIRMED', 'CANCELLED', 'COMPLETED');
CREATE TYPE "NotificationType" AS ENUM ('BOOKING_CONFIRMATION', 'APPOINTMENT_REMINDER');
CREATE TYPE "NotificationStatus" AS ENUM ('PENDING', 'SENT', 'FAILED');
CREATE TABLE "User" ("id" TEXT NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "role" "UserRole" NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Patient" ("id" TEXT NOT NULL, "displayName" TEXT NOT NULL, "userId" TEXT NOT NULL, CONSTRAINT "Patient_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Doctor" ("id" TEXT NOT NULL, "displayName" TEXT NOT NULL, "userId" TEXT NOT NULL, CONSTRAINT "Doctor_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Appointment" ("id" TEXT NOT NULL, "patientId" TEXT NOT NULL, "doctorId" TEXT NOT NULL, "appointmentTime" TIMESTAMP(3) NOT NULL, "status" "AppointmentStatus" NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Appointment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SlotReservation" ("appointmentId" TEXT NOT NULL, "doctorId" TEXT NOT NULL, "appointmentTime" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "SlotReservation_pkey" PRIMARY KEY ("appointmentId"));
CREATE TABLE "Notification" ("id" TEXT NOT NULL, "appointmentId" TEXT NOT NULL, "type" "NotificationType" NOT NULL, "status" "NotificationStatus" NOT NULL DEFAULT 'PENDING', "sentAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Notification_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "Patient_userId_key" ON "Patient"("userId");
CREATE UNIQUE INDEX "Doctor_userId_key" ON "Doctor"("userId");
CREATE INDEX "Appointment_patientId_idx" ON "Appointment"("patientId");
CREATE INDEX "Appointment_appointmentTime_idx" ON "Appointment"("appointmentTime");
CREATE INDEX "Appointment_status_idx" ON "Appointment"("status");
CREATE UNIQUE INDEX "SlotReservation_doctorId_appointmentTime_key" ON "SlotReservation"("doctorId", "appointmentTime");
CREATE UNIQUE INDEX "Notification_appointmentId_type_key" ON "Notification"("appointmentId", "type");
ALTER TABLE "Patient" ADD CONSTRAINT "Patient_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Doctor" ADD CONSTRAINT "Doctor_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "Doctor"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SlotReservation" ADD CONSTRAINT "SlotReservation_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "Doctor"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_appointmentId_fkey" FOREIGN KEY ("appointmentId") REFERENCES "Appointment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
